pub const entries: []const Template = @import("AvatarBattleTemplateTb");

pub const Template = struct {
    id: u32,
    avatar_piece_id: u32,
    hp_max: i32,
    health_growth: i32,
    attack: i32,
    attack_growth: i32,
    defence: i32,
    defence_growth: i32,
    crit: i32,
    crit_damage: i32,
    crit_res: i32,
    crit_damage_res: i32,
    pen_rate: i32,
    pen_delta: i32,
    luck: i32,
    stun: i32,
    break_stun: i32,
    element_abnormal_power: i32,
    sp_bar_point: i32,
    sp_recover: i32,
    element_mystery: i32,
    rbl: i32,
    rbl_correction_factor: i32,
    rbl_probability: i32,
    tags: []const []const u8,
    weapon_type: i32,
    element: []const i32,
    hit_type: []const i32,
    base_avatar_id: u32,
    rp_max: i32,
    rp_recover: i32,
    awake_ids: []const u32,
};
